name: Cypress E2E/Regression Tests
on:
  push:
    branches:    
      - main
      - develop
      - wenqi/e2e
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress
        uses: cypress-io/github-action@v4 
        with:
          command: npm run e2e:ci
      - name: Upload Snapshots
        uses: actions/upload-artifact@v3
        with:
          name: visual-regression-snapshots
          path: cypress/snapshots/
                